name: .NET Deploy Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    actions:
        runs-on: ubuntu-latest

        steps:
            - name: Setup .NET Core SDK
            uses: actions/setup-dotnet@v2.1.0
            - name: Restore dependencies
            run: dotnet restore
            - name: Build Testing
            run: dotnet build --no-restore
            - name: Test: Write config
            run: ./zeroProbe writeconfig
            - name: Test: Inspect config
            run: ./zeroProbe inspect
